_wandb:
    value:
        cli_version: 0.25.1
        e:
            q8zxc266bzo2xqdtec1m1q7bxvlmh4yk:
                codePath: sim_runner.py
                codePathLocal: sim_runner.py
                cpu_count: 4
                cpu_count_logical: 4
                disk:
                    /:
                        total: "105089261568"
                        used: "418054144"
                email: ceewye@outlook.com
                executable: /home/jules/.pyenv/versions/3.12.12/bin/python3
                git:
                    commit: 04863ad07cf09c2898d1ad597ff8736923d608fb
                    remote: https://github.com/ChaoYan/traffic-power-repair-sim-jules
                host: devbox
                memory:
                    total: "8345710592"
                os: Linux-6.8.0-x86_64-with-glibc2.39
                program: /app/sim_runner.py
                python: CPython 3.12.12
                root: /app
                startedAt: "2026-03-11T03:41:26.565515Z"
                writerId: q8zxc266bzo2xqdtec1m1q7bxvlmh4yk
        m: []
        python_version: 3.12.12
        t:
            "3":
                - 2
                - 13
            "4": 3.12.12
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
